/**
 * Flow service
 * 
 * Use this service to retrieve and update flows from the server.
 * A single flow runs as one data flopw, even though it is in separate tabs.
 */

export const getFlowById = async id => {

}

export const saveFlow = async flow => {
    // write flow to server
    // return id generated by server if needed
}

export const getFlowIds = async ()=> {
    // return list of flows available for the current user/account
}